name: 'Create Release'
description: 'Creates (and, optionally, deploys) a release.'
author: 'Octopus Deploy'

inputs:
  # Release creation options
  project:
    description: 'Name or ID of the project.'
    required: true
  package_version:
    description: 'Default version number of all packages to use for this release. Override per-package using `input_package`.'
    required: true
  version:
    description: 'Release number to use for the new release.'
    required: false
  channel:
    description: 'Name or ID of the channel to use for the new release. Omit this argument to automatically select the best channel.'
    required: false
  package:
    description: 'Version number to use for a package in the release. Format: StepName:Version or PackageID:Version or StepName:PackageName:Version. StepName, PackageID, and PackageName can be replaced with an asterisk. An asterisk will be assumed for StepName, PackageID, or PackageName if they are omitted.'
    required: false
  packages_folder:
    description: 'A folder containing NuGet packages from which we should get versions.'
    required: false
  release_notes:
    description: 'Release Notes for the new release. Styling with Markdown is supported.'
    required: false
  release_notes_file:
    description: 'Path to a file that contains Release Notes for the new release. Supports Markdown files.'
    required: false
  ignore_existing:
    description: 'Don''t create this release if there is already one with the same version number.'
    required: false
  ignore_channel_rules:
    description: 'Create the release ignoring any version rules specified by the channel.'
    required: false
  package_prerelease:
    description: 'Pre-release for latest version of all packages to use for this release.'
    required: false
  what_if:
    description: 'Perform a dry run but don''t actually create/deploy release.'
    required: false

  # Deployment
  deployment_progress:
    description: 'Show progress of the deployment'
    required: false
  deployment_force_package_download:
    description: 'Whether to force downloading of already installed packages. Default: `false`.'
    required: false
  wait_for_deployment:
    description: 'Whether to wait synchronously for deployment to finish.'
    required: false
  deployment_timeout:
    description: 'Specifies maximum time (timespan format) that the console session will wait for the deployment to finish. Default `00:10:00`. This will not stop the deployment. Requires `wait_for_deployment` parameter set.'
    required: false
  deployment_cancel_on_timeout:
    description: 'Whether to cancel the deployment if the deployment timeout is reached. Default: `false`.'
    required: false
  deployment_check_sleep_cycle:
    description: 'Specifies how much time (timespan format) should elapse between deployment status checks. Default: `00:00:10`'
    required: false
  deployment_guided_failure:
    description: 'Whether to use guided failure mode. Valid options are `True` or `False`. Default: setting from environment in Octopus.'
    required: false
  deployment_specific_machines:
    description: 'A comma-separated list of machine names to target in the deployed environment. If not specified all machines in the environment will be considered.'
    required: false
  deployment_exclude_machines:
    description: 'A comma-separated list of machine names to exclude in the deployed environment. If not specified all machines in the environment will be considered.'
    required: false
  deployment_force:
    description: 'If a project is configured to skip packages with already-installed versions, override this setting to force re-deployment. Default: `false`.'
    required: false
  deployment_skip_steps:
    description: 'A comma-separated list of step names to skip.'
    required: false
  deployment_no_raw_log:
    description: 'Don''t print the raw log of failed tasks'
    required: false
  deployment_variable:
    description: 'Redirect the raw log of failed tasks to a file'
    required: false
  deploy_at:
    description: 'A comma-separated list of values for any prompted variables in the format `Label:Value`. For JSON values, embedded quotation marks should be escaped with a backslash.'
    required: false
  no_deploy_after:
    description: 'Time at which deployment should start (scheduled deployment), specified as any valid DateTimeOffset format, and assuming the time zone is the current local time zone.'
    required: false
  deployment_tenant:
    description: 'A comma-separated list of tenants to create a deployment for or use `*` wildcard to deploy to all tenants who are ready for this release (according to lifecycle).'
    required: false
  deployment_tenant_tag:
    description: 'A comma-separated list of tenant tags for tenants to create a deployment for.'
    required: false
  deploy_to:
    description: 'A comma-separated list of environment names or IDs of the environments to automatically deploy to, e.g., ''Production'' or ''Environments-1'',''Environments-2''.'
    required: false

  octopus_server:
    description: 'The base URL for your Octopus Server, e.g., ''https://octopus.example.com/''.'
    required: true
  octopus_api_key:
    description: 'Your API key. Get this from the user profile page.'
    required: true
  debug:
    description: 'Enable debug logging'
    required: false
  ignore_ssl_errors:
    description: 'Set this flag if your Octopus Server uses HTTPS but the certificate is not trusted on this machine. Any certificate errors will be ignored. WARNING: this option may create a security vulnerability.'
    required: false
  timeout:
    description: 'Timeout in seconds for network operations. Default is `600`'
    required: false
  space:
    description: 'The name or ID of a space within which this command will be executed. The default space will be used if it is omitted.'
    required: false
  log_level:
    description: 'The log level. Valid options are `verbose`, `debug`, `information`, `warning`, `error` and `fatal`. Default: `debug`'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'package'
  color: 'gray-dark'