name: 'Pack'
description: 'Creates a package (.nupkg or .zip) from files on disk, without needing a .nuspec or .csproj.'
author: 'Octopus Deploy'

inputs:
  package_id:
    description: 'The ID of the package; e.g. MyCompany.MyApp'
    required: true
  format:
    description: 'Package format. Options are: NuPkg, Zip. Defaults to NuPkg, though we recommend Zip going forward'
    required: false
  version:
    description: 'The version of the package; must be a valid SemVer; defaults to a timestamp-based version'
    required: false
  out_folder:
    description: 'The folder into which the generated NuPkg file will be written; defaults to "."'
    required: false
  base_path:
    description: 'The root folder containing files and folders to pack; defaults to "."'
    required: false
  log_level:
    description: 'The log level. Valid options are verbose, debug, information, warning, error and fatal. Defaults to "debug".'
    required: false
  
  author:
    description: 'Add an author to the package metadata; defaults to the current user'
    required: false
  title:
    description: 'The title of the package'
    required: false
  description:
    description: 'A description of the package; defaults to a generic description'
    required: false
  release_notes:
    description: 'Release notes for this version of the package'
    required: false
  release_notes_file:
    description: 'A file containing release notes for this version of the package'
    required: false

  compression_level:
    description: 'Set compression level of package: none, fast, optimal (default).'
    required: false

  verbose:
    description: 'Verbose output'
    required: false
  include:
    description: 'Add a file pattern to include, relative to the base path e.g. /bin/- *.dll - if none are specified, defaults to **'
    required: false
  overwrite:
    description: 'Allow an existing package file of the same ID/version to be overwritten'
    required: false

runs:
  using: 'docker'
  image: 'octopusdeploy/octo:latest'
  args:
    - 'pack'
    - '--id=${{ inputs.package_id }}'
    - ${{if inputs.format }}:
      - '--format=${{ inputs.format }}'
    - ${{if inputs.version }}:
      - '--version=${{ inputs.version }}'
    - ${{if inputs.out_folder }}:
      - '--outFolder=${{ inputs.out_folder }}'
    - ${{if inputs.base_path }}:
      - '--basePath=${{ inputs.base_path }}'
    - ${{if inputs.log_level }}:
      - '--logLevel=${{ inputs.log_level }}'
    - ${{if inputs.author }}:
      - '--author=${{ inputs.author }}'
    - ${{if inputs.title }}:
      - '--title=${{ inputs.title }}'
    - ${{if inputs.description }}:
      - '--description=${{ inputs.description }}'
    - ${{if inputs.release_notes }}:
      - '--releaseNotes=${{ inputs.release_notes }}'
    - ${{if inputs.release_notes_file }}:
      - '--releaseNotesFile=${{ inputs.release_notes_file }}'
    - ${{if inputs.compression_level }}:
      - '--compressionLevel=${{ inputs.compression_level }}'
    - ${{if inputs.verbose }}:
      - '--verbose'
    - ${{if inputs.include }}:
      - '--include=${{ inputs.include }}'
    - ${{if inputs.overwrite }}:
      - '--overwrite'

branding:
  icon: 'package'
  color: 'gray-dark'