name: Integration tests
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  run-tests:
    name: Run tests
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04]
    
    steps:
      - uses: actions/checkout@v2

      - run: mkdir -p path/to/artifact
      
      - run: echo hello > path/to/artifact/hello_world.txt
      
      - name: Run pack action
        uses: ./pack
        with:
          package_id: 'Test'
          format: 'Zip'
          base_path: 'path/to/artifact'
          verbose: true
          overwrite: true
