name: Integration tests
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  run-tests:
    name: Run tests
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04]
    
    steps:
      - uses: actions/checkout@v2

      - run: mkdir -p path/to/artifact
      
      - run: echo hello > path/to/artifact/hello_world.txt
      
      - name: Run pack action
        uses: ./pack
        with:
          package_id: 'Test'
          version: '1.0.0'
          format: 'Zip'
          base_path: 'path/to/artifact'
          verbose: true
          overwrite: true
      
      - name: Push package to Octopus
        uses: ./push
        with:
          package: 'Test.1.0.0.zip'
          overwrite_mode: 'OverwriteExisting'
          octopus_server: ${{ secrets.OCTOPUS_URL }}
          octopus_api_key: ${{ secrets.OCTOPUS_API_KEY }}
          space: ${{ secrets.OCTOPUS_SPACE }}
