name: Octopus Integration tests
on:
  pull_request:
    branches:
      - master    
    paths:
      - 'octopus/*'
      - '**/octopus-integration-tests.yml'
      - '!**.md'
  push:
    branches:
      - master
    paths:
      - 'octopus/*'
      - '**/octopus-integration-tests.yml'
      - '!**.md'

env:
  ARTIFACT_PATH: 'path/to/artifact'
  OCTOPUS_SPACE_NAME: 'GitHub Actions Test'
  OCTOPUS_PROJECT_NAME: 'TestProject'
  OCTOPUS_PACKAGE_NAME: 'Test'
  OCTOPUS_PACKAGE_VERSION: '1.0.0'

jobs:
  run-tests:
    name: Run tests
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04]
    
    steps:
      - uses: actions/checkout@v2

      - run: mkdir -p ${{ env.ARTIFACT_PATH }}
      
      - run: echo hello > ${{ env.ARTIFACT_PATH }}/hello_world.txt
      
      - name: Run pack action
        uses: ./octopus/pack
        with:
          package_id: ${{ env.OCTOPUS_PACKAGE_NAME }}
          version: '${{ env.OCTOPUS_PACKAGE_VERSION }}+${{ github.sha }}.${{ matrix.os }}'
          format: 'Zip'
          base_path: ${{ env.ARTIFACT_PATH }}
          verbose: true
          overwrite: true
      
      - name: Push package to Octopus
        uses: ./octopus/push
        with:
          package: '${{ env.OCTOPUS_PACKAGE_NAME }}.${{ env.OCTOPUS_PACKAGE_VERSION }}+${{ github.sha }}.${{ matrix.os }}.zip'
          space: ${{ env.OCTOPUS_SPACE_NAME }}
          overwrite_mode: 'OverwriteExisting'
          octopus_server: ${{ secrets.OCTOPUS_URL }}
          octopus_api_key: ${{ secrets.OCTOPUS_API_KEY }}
      
      - name: Create release for '${{ env.OCTOPUS_PROJECT_NAME }}'
        uses: ./octopus/create-release
        with:
          project: ${{ env.OCTOPUS_PROJECT_NAME }}
          package_version: '${{ env.OCTOPUS_PACKAGE_VERSION }}+${{ github.sha }}.${{ matrix.os }}'
          version: '${{ env.OCTOPUS_PACKAGE_VERSION }}+${{ github.sha }}.${{ matrix.os }}'
          deployment_progress: true
          wait_for_deployment: true
          deploy_to: 'Dev'
          space: ${{ env.OCTOPUS_SPACE_NAME }}
          octopus_server: ${{ secrets.OCTOPUS_URL }}
          octopus_api_key: ${{ secrets.OCTOPUS_API_KEY }}
      
      - name: Deploy release latest release to 'Test'
        uses: ./octopus/deploy-release
        with:
          project: ${{ env.OCTOPUS_PROJECT_NAME }}
          release_number: '${{ env.OCTOPUS_PACKAGE_VERSION }}+${{ github.sha }}.${{ matrix.os }}'
          deploy_to: 'Test'
          progress: true
          wait_for_deployment: true
          space: ${{ env.OCTOPUS_SPACE_NAME }}
          octopus_server: ${{ secrets.OCTOPUS_URL }}
          octopus_api_key: ${{ secrets.OCTOPUS_API_KEY }}
